#
# Module manifest for module 'TreeStore.JsonFS'
#
# Generated by: github.com/wgross
#
# Generated on: 24.07.2022
#

@{
    RootModule = 'TreeStore.JsonFS.dll'
    ModuleVersion = '0.1.0'
    GUID = '27ca097c-25c2-465e-8e93-b46a602cf9cd'
    Author = 'github.com/wgross'
    Copyright = '(c) github.com/wgross. All rights reserved.'
    Description = 'Mount JSON files as PowerShell drives'
}

